export type Tool = {
  slug: string;
  name: string;
  description: string;
  category: 'developer' | 'image' | 'pdf' | 'ai' | 'privacy' | 'generator';
  /** Hub pages this tool should ALSO appear on (in addition to its primary category). */
  secondaryCategories?: Array<'developer' | 'image' | 'pdf' | 'ai' | 'privacy' | 'generator'>;
  icon: string;
  keywords: string[];
  available: boolean;
};

export const TOOLS: Tool[] = [
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON. Runs in your browser.',
    category: 'developer',
    icon: '{ }',
    keywords: ['json', 'format', 'validator', 'minify', 'beautify'],
    available: true,
  },
  {
    slug: 'base64',
    name: 'Base64 Encoder',
    description: 'Encode or decode Base64 strings. Supports UTF-8 and files.',
    category: 'developer',
    icon: '⇄',
    keywords: ['base64', 'encode', 'decode', 'converter'],
    available: true,
  },
  {
    slug: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate customizable QR codes. Download as PNG or SVG.',
    category: 'generator',
    secondaryCategories: ['developer'],
    icon: '▣',
    keywords: ['qr code', 'generator', 'png', 'svg'],
    available: true,
  },
  {
    slug: 'pdf-merger',
    name: 'PDF Merger',
    description: 'Combine multiple PDFs into one. Files never leave your device.',
    category: 'pdf',
    icon: '📄',
    keywords: ['pdf', 'merge', 'combine', 'join', 'concatenate'],
    available: true,
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress JPG, PNG, WebP locally with adjustable quality. Zero uploads.',
    category: 'image',
    icon: '🖼',
    keywords: ['image', 'compress', 'optimize', 'jpg', 'png', 'webp'],
    available: true,
  },
  {
    slug: 'background-remover',
    name: 'Background Remover',
    description: 'Remove image backgrounds locally with WebGPU AI. No upload, no API.',
    category: 'ai',
    secondaryCategories: ['image'],
    icon: '✨',
    keywords: ['background', 'remove', 'ai', 'webgpu', 'transparent', 'cutout'],
    available: true,
  },
  {
    slug: 'audio-transcriber',
    name: 'Audio Transcriber',
    description: 'Speech-to-text via Whisper, running on your device. 99+ languages. No upload, no API.',
    category: 'ai',
    icon: '🎤',
    keywords: ['transcription', 'speech to text', 'whisper', 'ai', 'subtitles', 'webgpu'],
    available: true,
  },
  {
    slug: 'pdf-splitter',
    name: 'PDF Splitter',
    description: 'Split a PDF into single pages or extract a page range. Runs in your browser.',
    category: 'pdf',
    icon: '✂',
    keywords: ['pdf', 'split', 'extract', 'pages', 'separate'],
    available: true,
  },
  {
    slug: 'exif-remover',
    name: 'EXIF Remover',
    description: 'Strip GPS, camera and timestamp metadata from images. Privacy-first, local-only.',
    category: 'privacy',
    secondaryCategories: ['image'],
    icon: '🛡',
    keywords: ['exif', 'metadata', 'remove', 'privacy', 'gps', 'strip'],
    available: true,
  },
  {
    slug: 'color-palette',
    name: 'Color Palette Extractor',
    description: 'Extract dominant colors from any image. Copy HEX, RGB, HSL. Zero uploads.',
    category: 'generator',
    secondaryCategories: ['image'],
    icon: '🎨',
    keywords: ['color', 'palette', 'extract', 'dominant', 'hex', 'designer'],
    available: true,
  },
  {
    slug: 'image-converter',
    name: 'Image Format Converter',
    description: 'Batch convert JPG ↔ PNG ↔ WebP ↔ AVIF. Drop, choose format, download. Local.',
    category: 'image',
    icon: '⇆',
    keywords: ['image', 'convert', 'jpg', 'png', 'webp', 'avif', 'batch'],
    available: true,
  },
  {
    slug: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Shrink PDF size with adjustable image quality. Strong (re-render) or Keep text mode. No upload.',
    category: 'pdf',
    icon: '🗜',
    keywords: ['pdf', 'compress', 'reduce size', 'shrink', 'optimize'],
    available: true,
  },
  {
    slug: 'pdf-rotator',
    name: 'PDF Rotator',
    description: 'Rotate all pages or a specific range 90 / 180 / 270 degrees. Runs in your browser.',
    category: 'pdf',
    icon: '↻',
    keywords: ['pdf', 'rotate', 'turn', 'pages'],
    available: true,
  },
  {
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Combine JPG or PNG images into a single PDF. Reorder, pick page size, adjust margin. Local.',
    category: 'pdf',
    icon: '🖼',
    keywords: ['jpg', 'png', 'to pdf', 'image to pdf', 'convert', 'combine'],
    available: true,
  },
  {
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert each PDF page to JPG, PNG, or WebP at chosen resolution. Download as ZIP. Local.',
    category: 'pdf',
    icon: '📷',
    keywords: ['pdf', 'to jpg', 'to png', 'to webp', 'extract images', 'convert'],
    available: true,
  },
  {
    slug: 'pdf-unlocker',
    name: 'PDF Unlocker',
    description: 'Remove the password from a PDF when you know the password. Runs in your browser — password never leaves the device.',
    category: 'pdf',
    icon: '🔓',
    keywords: ['pdf', 'unlock', 'remove password', 'decrypt'],
    available: true,
  },
  {
    slug: 'pdf-protector',
    name: 'PDF Protector',
    description: 'Add an AES-128 password to a PDF. Encryption happens entirely in your browser. No upload.',
    category: 'pdf',
    icon: '🔒',
    keywords: ['pdf', 'password', 'encrypt', 'protect', 'secure'],
    available: true,
  },
  {
    slug: 'pdf-watermark',
    name: 'PDF Watermark',
    description: 'Add a text watermark to every page of a PDF — adjustable position, color, size and opacity. Local.',
    category: 'pdf',
    icon: '💧',
    keywords: ['pdf', 'watermark', 'text', 'confidential', 'draft'],
    available: true,
  },
  {
    slug: 'pdf-ocr',
    name: 'PDF OCR',
    description: 'Make scanned PDFs searchable with Tesseract, or extract plain text. 8 languages, runs in your browser.',
    category: 'ai',
    secondaryCategories: ['pdf'],
    icon: '👁',
    keywords: ['ocr', 'pdf', 'searchable', 'tesseract', 'scan', 'text recognition'],
    available: true,
  },
  {
    slug: 'pdf-organizer',
    name: 'PDF Organizer',
    description: 'Reorder, delete, and reorganize PDF pages with visual thumbnails. Local-only.',
    category: 'pdf',
    icon: '⫴',
    keywords: ['pdf', 'organize', 'reorder', 'delete pages', 'rearrange'],
    available: true,
  },
  {
    slug: 'pdf-page-numbers',
    name: 'PDF Page Numbers',
    description: 'Add page numbers to every page. Format, position, color, starting number — all configurable.',
    category: 'pdf',
    icon: '#',
    keywords: ['pdf', 'page numbers', 'numbering', 'pagination'],
    available: true,
  },
  {
    slug: 'pdf-cropper',
    name: 'PDF Cropper',
    description: 'Trim margins off every page. Percent or points. Runs in your browser.',
    category: 'pdf',
    icon: '✂',
    keywords: ['pdf', 'crop', 'trim', 'margins'],
    available: true,
  },
];

export const CATEGORIES = {
  developer: { label: 'Developer', color: 'brand' },
  image: { label: 'Image', color: 'accent' },
  pdf: { label: 'PDF', color: 'brand' },
  ai: { label: 'AI', color: 'accent' },
  privacy: { label: 'Privacy', color: 'success' },
  generator: { label: 'Generator', color: 'brand' },
} as const;
